/** Art Director SVG pack v1 — files under public/assets/{cats,furniture,ui}. */

export const ART_STROKE = "#2B2A28";
export const FUR_CREAM = "#FFF8F0";
export const FUR_GINGER = "#D38B5D";
export const FUR_SLATE = "#5A5E6B";
export const FUR_TUX = "#3A3D48";
export const FUR_CLAY = "#E8A89A";

export const CAT_ASSETS = {
  cream_loaf_48: "/assets/cats/cream_loaf_48.svg",
  cream_loaf_72: "/assets/cats/cream_loaf_72.svg",
  ginger_loaf_48: "/assets/cats/ginger_loaf_48.svg",
  ginger_loaf_72: "/assets/cats/ginger_loaf_72.svg",
  ginger_loaf_160: "/assets/cats/ginger_loaf_160.svg",
  slate_loaf_48: "/assets/cats/ink_loaf_48.svg",
  slate_loaf_72: "/assets/cats/ink_loaf_72.svg",
  ink_loaf_48: "/assets/cats/ink_loaf_48.svg",
  ink_loaf_72: "/assets/cats/ink_loaf_72.svg",
  color_gray_loaf_48: "/assets/cats/color_gray_loaf_48.svg",
  color_gray_loaf_72: "/assets/cats/color_gray_loaf_72.svg",
  gray_loaf_48: "/assets/cats/gray_loaf_48.svg",
  gray_loaf_72: "/assets/cats/gray_loaf_72.svg",
  friend_002_loaf_48: "/assets/cats/friend_002_loaf_48.svg",
  friend_002_loaf_72: "/assets/cats/friend_002_loaf_72.svg",
  calico_loaf_48: "/assets/cats/calico_loaf_48.svg",
  calico_loaf_72: "/assets/cats/calico_loaf_72.svg",
  calico_belly_72: "/assets/cats/calico_belly_72.svg",
  orange_belly_72: "/assets/cats/orange_belly_72.svg",
  gray_belly_72: "/assets/cats/gray_belly_72.svg",
  black_belly_72: "/assets/cats/black_belly_72.svg",
  tux_loaf_48: "/assets/cats/tux_loaf_48.svg",
  tux_loaf_72: "/assets/cats/tux_loaf_72.svg",
  friend_004_loaf_48: "/assets/cats/friend_004_loaf_48.svg",
  friend_004_loaf_72: "/assets/cats/friend_004_loaf_72.svg",
  ghost_loaf_48: "/assets/cats/ghost_loaf_48.svg",
  ghost_loaf_72: "/assets/cats/ghost_loaf_72.svg",
  mist_loaf_48: "/assets/cats/mist_loaf_48.svg",
  mist_loaf_72: "/assets/cats/mist_loaf_72.svg",
  friend_006_loaf_48: "/assets/cats/mist_loaf_48.svg",
  friend_006_loaf_72: "/assets/cats/mist_loaf_72.svg",
  pepper_loaf_48: "/assets/cats/pepper_loaf_48.svg",
  pepper_loaf_72: "/assets/cats/pepper_loaf_72.svg",
  friend_007_loaf_48: "/assets/cats/pepper_loaf_48.svg",
  friend_007_loaf_72: "/assets/cats/pepper_loaf_72.svg",
  pumpkin_loaf_48: "/assets/cats/pumpkin_loaf_48.svg",
  pumpkin_loaf_72: "/assets/cats/pumpkin_loaf_72.svg",
  friend_008_loaf_48: "/assets/cats/pumpkin_loaf_48.svg",
  friend_008_loaf_72: "/assets/cats/pumpkin_loaf_72.svg",
  shadow_loaf_48: "/assets/cats/shadow_loaf_48.svg",
  shadow_loaf_72: "/assets/cats/shadow_loaf_72.svg",
  friend_009_loaf_48: "/assets/cats/shadow_loaf_48.svg",
  friend_009_loaf_72: "/assets/cats/shadow_loaf_72.svg",
  noodle_loaf_48: "/assets/cats/noodle_loaf_48.svg",
  noodle_loaf_72: "/assets/cats/noodle_loaf_72.svg",
  friend_010_loaf_48: "/assets/cats/noodle_loaf_48.svg",
  friend_010_loaf_72: "/assets/cats/noodle_loaf_72.svg",
  clover_loaf_48: "/assets/cats/clover_loaf_48.svg",
  clover_loaf_72: "/assets/cats/clover_loaf_72.svg",
  friend_011_loaf_48: "/assets/cats/clover_loaf_48.svg",
  friend_011_loaf_72: "/assets/cats/clover_loaf_72.svg",
  ash_loaf_48: "/assets/cats/ash_loaf_48.svg",
  ash_loaf_72: "/assets/cats/ash_loaf_72.svg",
  friend_012_loaf_48: "/assets/cats/ash_loaf_48.svg",
  friend_012_loaf_72: "/assets/cats/ash_loaf_72.svg",
  oak_loaf_48: "/assets/cats/oak_loaf_48.svg",
  oak_loaf_72: "/assets/cats/oak_loaf_72.svg",
  friend_013_loaf_48: "/assets/cats/oak_loaf_48.svg",
  friend_013_loaf_72: "/assets/cats/oak_loaf_72.svg",
  dumpling_loaf_48: "/assets/cats/dumpling_loaf_48.svg",
  dumpling_loaf_72: "/assets/cats/dumpling_loaf_72.svg",
  friend_014_loaf_48: "/assets/cats/dumpling_loaf_48.svg",
  friend_014_loaf_72: "/assets/cats/dumpling_loaf_72.svg",
  stripe_loaf_48: "/assets/cats/stripe_loaf_48.svg",
  stripe_loaf_72: "/assets/cats/stripe_loaf_72.svg",
  friend_015_loaf_48: "/assets/cats/stripe_loaf_48.svg",
  friend_015_loaf_72: "/assets/cats/stripe_loaf_72.svg",
  cloud_loaf_48: "/assets/cats/cloud_loaf_48.svg",
  cloud_loaf_72: "/assets/cats/cloud_loaf_72.svg",
  friend_016_loaf_48: "/assets/cats/cloud_loaf_48.svg",
  friend_016_loaf_72: "/assets/cats/cloud_loaf_72.svg",
  donna_loaf_48: "/assets/cats/donna_loaf_48.svg",
  donna_loaf_72: "/assets/cats/donna_loaf_72.svg",
  friend_017_loaf_48: "/assets/cats/donna_loaf_48.svg",
  friend_017_loaf_72: "/assets/cats/donna_loaf_72.svg",
  sunny_loaf_48: "/assets/cats/sunny_loaf_48.svg",
  sunny_loaf_72: "/assets/cats/sunny_loaf_72.svg",
  friend_018_loaf_48: "/assets/cats/sunny_loaf_48.svg",
  friend_018_loaf_72: "/assets/cats/sunny_loaf_72.svg",
  nigel_loaf_48: "/assets/cats/nigel_loaf_48.svg",
  nigel_loaf_72: "/assets/cats/nigel_loaf_72.svg",
  friend_019_loaf_48: "/assets/cats/nigel_loaf_48.svg",
  friend_019_loaf_72: "/assets/cats/nigel_loaf_72.svg",
  bean_loaf_48: "/assets/cats/bean_loaf_48.svg",
  bean_loaf_72: "/assets/cats/bean_loaf_72.svg",
  friend_020_loaf_48: "/assets/cats/bean_loaf_48.svg",
  friend_020_loaf_72: "/assets/cats/bean_loaf_72.svg",
} as const;

export const FURN_ASSETS = {
  boxBed: "/assets/furniture/boxBed.svg",
  swing: "/assets/furniture/swing.svg",
  scratcher: "/assets/furniture/scratcher.svg",
  miniTree: "/assets/furniture/miniTree.svg",
  yarnSwing: "/assets/furniture/yarnSwing.svg",
  sunCushion: "/assets/furniture/sunCushion.svg",
  postBell: "/assets/furniture/postBell.svg",
  fence: "/assets/furniture/fence.svg",
  fountain: "/assets/furniture/fountain.svg",
  cosmosStem: "/assets/furniture/cosmosStem.svg",
  clematisTrellis: "/assets/furniture/clematisTrellis.svg",
  wisteriaArbor: "/assets/furniture/wisteriaArbor.svg",
  anemoneBowl: "/assets/furniture/anemoneBowl.svg",
} as const;

export const UI_ASSETS = {
  btn_primary: "/assets/ui/btn_primary.svg",
  input_name: "/assets/ui/input_name.svg",
  fail_mark: "/assets/ui/fail_mark.svg",
  fail_empty: "/assets/ui/fail_empty.svg",
  star_anemone: "/assets/ui/star_anemone.svg",
  star_wisteria: "/assets/ui/star_wisteria.svg",
  star_clematis: "/assets/ui/star_clematis.svg",
  star_cosmos: "/assets/ui/star_cosmos.svg",
  star_buttercup: "/assets/ui/star_buttercup.svg",
  star_primrose: "/assets/ui/star_primrose.svg",
  star_heather: "/assets/ui/star_heather.svg",
  star_marigold: "/assets/ui/star_marigold.svg",
  hand_cursor: "/assets/ui/hand_cursor.svg",
  bubble_bang: "/assets/ui/bubble_bang.svg",
  icon_close: "/assets/ui/icon_close.svg",
  gate_orange: "/assets/gates/gate_orange.svg",
  gate_gray: "/assets/gates/gate_gray.svg",
  gate_black: "/assets/gates/gate_black.svg",
} as const;

export const GATE_ASSETS: Record<"orange" | "gray" | "black", string> = {
  orange: "/assets/gates/gate_orange.svg",
  gray: "/assets/gates/gate_gray.svg",
  black: "/assets/gates/gate_black.svg",
};
